### ISSUE TITLE
Invalid Anonymous User

### ISSUE THREAD

**Issue by gsequeira-hu** [1Flow-Inc/1flow-web-sdk#1]
Hi sorry but my english is bad.

I have a problem when i use 1flow and call to fuction `logUser`. In Development environment the request respond with 200 but in other environment like test environment it doesn't work responde 400 bad request. I use the same oneflow apiKey.

<img width="476" alt="Captura de Pantalla 2022-12-05 a la(s) 17 52 48" src="https://user-images.githubusercontent.com/93542548/205740723-7ca1473b-4ec8-4e54-92c5-202c285e43ce.png">

<img width="478" alt="Captura de Pantalla 2022-12-05 a la(s) 17 50 32" src="https://user-images.githubusercontent.com/93542548/205740301-90f289e7-5bdc-4c4b-ad3f-196158892e70.png">

<img width="433" alt="Captura de Pantalla 2022-12-05 a la(s) 17 50 42" src="https://user-images.githubusercontent.com/93542548/205740303-b1e1f4b3-9f12-4aec-87e3-ce1a2b9b2fd6.png">

what is the problem? thanks.

**Comment by ShadowWalker2014** [comment]
Thanks for reporting this issue! A member of our team will review this and get back to you soon.

**Comment by namit1Flow** [comment]
Hi @guilleHumand ,

Please clean your development server's cache and local storage and try again.
It seems to be a cache issue and it will be fixed after clearing the cache of your browser.

Please try it and let us know if you require further assistance.

**Comment by gsequeira-hu** [comment]
Thanks @namit1Flow your solution worked.
